export { default as CommunityEditGeneral } from './CommunityEditGeneral'
export { default as CommunityEditThumbnail } from './CommunityEditThumbnail'
export { default as CommunityEditCourse } from './CommunityEditCourse'
export { default as CommunityEditModeration } from './CommunityEditModeration'
export { default as CommunityEditAccess } from './CommunityEditAccess'
export { default as CommunityEditPlans } from './CommunityEditPlans'
export { default as CommunityEditMembership } from './CommunityEditMembership'
export { default as CommunityEditPlanAssignments } from './CommunityEditPlanAssignments'
